version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-image
    versions:
    - 2.11.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby
    versions:
    - 2.32.10
    - 2.32.11
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: "@quarkly/widgets"
    versions:
    - 0.2.44
    - 0.2.47
  - dependency-name: "@quarkly/components"
    versions:
    - 0.2.46
    - 0.2.47
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.0
